package dante.android.glidesharedtransition

/**
 * @author Du Wenyu
 * 2019-09-06
 */
object FakeData {

    fun getData() = arrayListOf(
            Image("https://th.wallhaven.cc/small/4o/4o1g17.jpg", "https://w.wallhaven.cc/full/4o/wallhaven-4o1g17.jpg"), Image("https://th.wallhaven.cc/small/4x/4xl98l.jpg", "https://w.wallhaven.cc/full/4x/wallhaven-4xl98l.jpg"), Image("https://th.wallhaven.cc/small/3k/3kdxov.jpg", "https://w.wallhaven.cc/full/3k/wallhaven-3kdxov.jpg"), Image("https://th.wallhaven.cc/small/nr/nrlx9w.jpg", "https://w.wallhaven.cc/full/nr/wallhaven-nrlx9w.jpg"), Image("https://th.wallhaven.cc/small/4d/4d66j0.jpg", "https://w.wallhaven.cc/full/4d/wallhaven-4d66j0.jpg"), Image("https://th.wallhaven.cc/small/nm/nm1rl9.jpg", "https://w.wallhaven.cc/full/nm/wallhaven-nm1rl9.jpg"),
            Image("https://th.wallhaven.cc/small/j5/j55evw.jpg", "https://w.wallhaven.cc/full/j5/wallhaven-j55evw.jpg"), Image("https://th.wallhaven.cc/small/83/83319o.jpg", "https://w.wallhaven.cc/full/83/wallhaven-83319o.jpg"), Image("https://th.wallhaven.cc/small/ne/ne85kr.jpg", "https://w.wallhaven.cc/full/ne/wallhaven-ne85kr.jpg"), Image("https://th.wallhaven.cc/small/nk/nk8oyq.jpg", "https://w.wallhaven.cc/full/nk/wallhaven-nk8oyq.jpg"), Image("https://th.wallhaven.cc/small/43/432xrv.jpg", "https://w.wallhaven.cc/full/43/wallhaven-432xrv.jpg"), Image("https://th.wallhaven.cc/small/4g/4gvxye.jpg", "https://w.wallhaven.cc/full/4g/wallhaven-4gvxye.jpg"),
            Image("https://th.wallhaven.cc/small/g8/g82287.jpg", "https://w.wallhaven.cc/full/g8/wallhaven-g82287.jpg"), Image("https://th.wallhaven.cc/small/42/42qxvx.jpg", "https://w.wallhaven.cc/full/42/wallhaven-42qxvx.jpg"), Image("https://th.wallhaven.cc/small/01/01evw4.jpg", "https://w.wallhaven.cc/full/01/wallhaven-01evw4.jpg"), Image("https://th.wallhaven.cc/small/45/45yrv3.jpg", "https://w.wallhaven.cc/full/45/wallhaven-45yrv3.jpg"), Image("https://th.wallhaven.cc/small/od/odxkz5.jpg", "https://w.wallhaven.cc/full/od/wallhaven-odxkz5.jpg"), Image("https://th.wallhaven.cc/small/4y/4y1xqd.jpg", "https://w.wallhaven.cc/full/4y/wallhaven-4y1xqd.jpg"),
            Image("https://th.wallhaven.cc/small/4l/4lw35q.jpg", "https://w.wallhaven.cc/full/4l/wallhaven-4lw35q.jpg"), Image("https://th.wallhaven.cc/small/4l/4llej2.jpg", "https://w.wallhaven.cc/full/4l/wallhaven-4llej2.jpg"), Image("https://th.wallhaven.cc/small/eo/eoe91k.jpg", "https://w.wallhaven.cc/full/eo/wallhaven-eoe91k.jpg"), Image("https://th.wallhaven.cc/small/4l/4le3y0.jpg", "https://w.wallhaven.cc/full/4l/wallhaven-4le3y0.jpg"), Image("https://th.wallhaven.cc/small/yj/yjewlg.jpg", "https://w.wallhaven.cc/full/yj/wallhaven-yjewlg.jpg"), Image("https://th.wallhaven.cc/small/od/odzkd9.jpg", "https://w.wallhaven.cc/full/od/wallhaven-odzkd9.jpg"),
            Image("https://th.wallhaven.cc/small/nr/nro3jn.jpg", "https://w.wallhaven.cc/full/nr/wallhaven-nro3jn.jpg"), Image("https://th.wallhaven.cc/small/0w/0w5gjp.jpg", "https://w.wallhaven.cc/full/0w/wallhaven-0w5gjp.jpg"), Image("https://th.wallhaven.cc/small/42/421vvg.jpg", "https://w.wallhaven.cc/full/42/wallhaven-421vvg.jpg"), Image("https://th.wallhaven.cc/small/n6/n65l57.jpg", "https://w.wallhaven.cc/full/n6/wallhaven-n65l57.jpg"), Image("https://th.wallhaven.cc/small/47/47qwq3.jpg", "https://w.wallhaven.cc/full/47/wallhaven-47qwq3.jpg"), Image("https://th.wallhaven.cc/small/48/483jgk.jpg", "https://w.wallhaven.cc/full/48/wallhaven-483jgk.jpg"),
            Image("https://th.wallhaven.cc/small/qd/qd9ggl.jpg", "https://w.wallhaven.cc/full/qd/wallhaven-qd9ggl.jpg"), Image("https://th.wallhaven.cc/small/01/01vdp3.jpg", "https://w.wallhaven.cc/full/01/wallhaven-01vdp3.jpg"), Image("https://th.wallhaven.cc/small/0w/0wemg6.jpg", "https://w.wallhaven.cc/full/0w/wallhaven-0wemg6.jpg"), Image("https://th.wallhaven.cc/small/x1/x1pxlv.jpg", "https://w.wallhaven.cc/full/x1/wallhaven-x1pxlv.jpg"), Image("https://th.wallhaven.cc/small/wy/wy66mp.jpg", "https://w.wallhaven.cc/full/wy/wallhaven-wy66mp.jpg"), Image("https://th.wallhaven.cc/small/4g/4g52dq.jpg", "https://w.wallhaven.cc/full/4g/wallhaven-4g52dq.jpg"))
}